<?php
//https://www.rakeshjesadiya.com/add-custom-tab-in-admin-sales-order-view-magento-2/
/*
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $Registry = $objectManager->get('Magento\Framework\Registry');

    $EntityId = $Registry->registry('current_order')->getEntityId();
    $OrderNo = $Registry->registry('current_order')->getIncrementId();  
    
    $storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
    $baseurl = $storeManager->getStore()->getBaseUrl();
    
    $order = $objectManager->create('\Magento\Sales\Model\OrderRepository')->get($EntityId);
    $payment = $order->getPayment();
    $paymentmethod = $payment->getMethod() ;

    $order = $objectManager->create('Magento\Sales\Model\Order')->loadByIncrementId($OrderNo);  
    $payment = $order->getPayment();
    $method = $payment->getMethodInstance();
    $methodTitle = $method->getTitle();
        
    $kverify_status = 'N';
    if ($paymentmethod =='shopeepay'){
        $kverify_status = 'Y';
    }
    */

    /**
     * @var \PaySolutions\Base\Block\Order\View\Inquiry $block
     */

    echo $block->sayHello();
?>

<script>
    function shopeepayVerify (p_order_no){

    jQuery('body').loader('show');
    

       jQuery.ajax({
            url: '<?php echo $baseurl;?>shopeepay/jumpapp/orderinfo',
            method: 'POST',
            dataType: 'json',
            data: {
                'order_no' : '<?php echo $OrderNo;?>'
            },
            success: function(data){
              console.log(JSON.stringify(data));
              
              var obj = JSON.parse(JSON.stringify(data));

                if(obj.debug_msg == 'server error' ){
                        require([
                                'jquery',
                                'Magento_Ui/js/modal/alert'
                            ],
                            function($, alert) {
                            
                                alert({
                                        title: "Order No: <?php echo $OrderNo;?> ",
                                        content: '<span style="color:black; font-size:15px">Server Error กรุณาลองกดใหม่<br>error_code: '+obj.errcode+'<br>debug_msg: '+obj.debug_msg+'</span>',
                                        autoOpen: true,
                                        clickableOverlay: false,
                                        focus: ""
                                    });                                
                                
                            
                                
                                jQuery('body').loader('hide');
                            }
                        ); 
                        
                }else if (obj.debug_msg == 'success' ){
                

                        require([
                                'jquery',
                                'Magento_Ui/js/modal/alert'
                            ],
                            function($, alert) {
                             
                                   alert({
                                        title: "Order No: <?php echo $OrderNo;?> ",
                                        content: '<span style="color:blue; font-size:15px">This order is already paid.<br>error_code: '+obj.errcode+'<br>debug_msg: '+obj.debug_msg+'</span>',
                                        autoOpen: true,
                                        clickableOverlay: false,
                                        focus: ""
                                    });                                
                                
                              
                                
                                 jQuery('body').loader('hide');
                            }
                        ); 
                        
                }else{
                                    

                    require([
                            'jquery',
                            'Magento_Ui/js/modal/alert'
                        ],
                        function($, alert) {
                           alert({
                                title: "Order No: <?php echo $OrderNo;?> ",
                                content: '<span style="color:red; font-size:15px">This order is unpaid..<br>error_code: '+obj.errcode+'<br>debug_msg: '+obj.debug_msg+'</span>',
                                autoOpen: true,
                                clickableOverlay: false,
                                focus: ""
                            });
                             jQuery('body').loader('hide');
                        }
                    ); 
                              
                  
              }
              
            },
            error: function(XMLHttpRequest, textStatus, errorThrown) { 
               console.log("Status: " + textStatus); console.log("Error: " + errorThrown); 

                    require([
                            'jquery',
                            'Magento_Ui/js/modal/alert'
                        ],
                        function($, alert) {
                           alert({
                                title: "Order No: <?php echo $OrderNo;?> ",
                                content: '<span style="color:red; font-size:15px">!! ERROR: Cannot connect to service.</span>',
                                autoOpen: true,
                                clickableOverlay: false,
                                focus: ""
                            });
                             jQuery('body').loader('hide');
                        }
                    );                 
                
            } 
          });
        



    }
    
    
    require([
        'jquery'
    ], function($){
    

        $('.order-payment-method-title').html( '<a href="javascript:void(0)" onclick="shopeepayVerify(\'<?php echo $OrderNo;?>\')">'+$('.order-payment-method-title').html()+'</a>');
    
    });


</script>
